version: 2

sources:
  - name: public
    tables:
      - name: walmart_raw
        description: Raw transactional data from Walmart's customer purchase history
        columns:
          - name: user_id
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null
          - name: purchase
            tests:
              - not_null
              - accepted_values:
                  values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
                  severity: warn  # just to show how accepted_values work, we'll fix it later

models:
  - name: fct_sales
    columns:
      - name: user_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: user_id


